### ISSUE TITLE
Only owner can remove publication

### ISSUE THREAD

**Issue by Boberneprotiv** [ghosts-network/gateway#22]
**Describe the bug**
Not only author of publication can remove it.

**To Reproduce**
1. Create publication as User1
2. Delete it as User2

**Expected behavior**
Delete trying should return 403 status code

**Comment by Sekir0** [comment]
must be smt like this?
i think it's can be simplified
https://github.com/ghosts-network/gateway/blob/00e9e2ce3681d96156b7ef8567da820c2304ca86/Infrastructure/GhostNetwork.Infrastructure.Repository/NewsFeedStorage.cs#L145

**Comment by Boberneprotiv** [comment]
For now a don’t like how NewsFeedStorage looks like at all, but your solution is good enough
