### ISSUE TITLE
Change X-HasMore header type

### ISSUE THREAD

**Issue by Boberneprotiv** [ghosts-network/gateway#24]
**Describe the bug**
Wrong type of X-HasMore in swagger.json

**To Reproduce**
1. Open https://api.gn.boberneprotiv.com/swagger/v1/swagger.json
2. Find definition for X-HasMore header in any request
3. X-HasMore.schema.type is "String"

**Expected behavior**
X-HasMore.schema.type is "String" should be "boolean"

**Comment by prktkn** [comment]
Hello! Should the header type be capitalized or should it be in lowercase?

**Comment by Boberneprotiv** [comment]
Hi! By default Swashbuckle writes type of field in lower case, so we also should use lower case
