### ISSUE TITLE
502 error after positive login

### ISSUE THREAD

**Issue by Artem100** [ghosts-network/gateway#47]
**To Reproduce**
1. Go to '[Login page](ghost-network.boberneprotiv.com)'
2. Input positive user creds: some2390131@yopmail.com/a12345Z!
3. Click login

**Actual behavior**
502 error
redirect url: https://accounts.ghost-network.boberneprotiv.com/Account/Login?ReturnUrl=/connect/authorize/callback?client_id=angular_spa_prod&redirect_uri=https%3A%2F%2Fghost-network.boberneprotiv.com%2Fauth-callback&response_type=id_token%20token&scope=openid%20profile%20api&state=cc93dba516214e1b8771d25caef65537&nonce=5b936e04f29c482bb1478056dd434522

**Expected behavior**
Account page

**Comment by Boberneprotiv** [comment]
Whenever service is down it returns 502. For this deployment I have too small amount of RAM, so there is noting to fix. Might use bigger instance in case, problem will be critical
