### ISSUE TITLE
Can't open login page

### ISSUE THREAD

**Issue by Artem100** [ghosts-network/gateway#60]
**To Reproduce**
Open url: https://accounts.ghost-network.boberneprotiv.com

**Expected behavior**
Login page is opened

**Actual behavior**
User is redirecred to: http://127.0.0.1:6620/connect/authorize?client_id=angular_spa_prod&redirect_uri=https%3A%2F%2Fghost-network.boberneprotiv.com%2Fauth-callback&response_type=id_token%20token&scope=openid%20profile%20api&state=d206e4748f8c459aab1cce322d27a761&nonce=a8a4733694a94df8ae40f3c1a0f0ecb7

**Comment by volodymyr-borodin** [comment]
Thanks for bug. There were problems with deployment
